QT.gifimage.VERSION = 0.1.0
QT.gifimage.name = QtGifImage
QT.gifimage.module = Qt5GifImage
QT.gifimage.libs = $$QT_MODULE_LIB_BASE
QT.gifimage.includes = $$QT_MODULE_INCLUDE_BASE $$QT_MODULE_INCLUDE_BASE/QtGifImage
QT.gifimage.frameworks =
QT.gifimage.bins = $$QT_MODULE_BIN_BASE
QT.gifimage.depends = core gui
QT.gifimage.uses =
QT.gifimage.module_config = v2
QT.gifimage.DEFINES = QT_GIFIMAGE_LIB
QT.gifimage.enabled_features =
QT.gifimage.disabled_features =
QT_CONFIG +=
QT_MODULES += gifimage
